// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Satizen_Api.Data;

#nullable disable

namespace Satizen_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240528141115_NombredelaMigracion")]
    partial class NombredelaMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Satizen_Api.Models.Asignacion", b =>
                {
                    b.Property<int>("idAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAsignacion"));

                    b.Property<int>("idPersonal")
                        .HasColumnType("int");

                    b.Property<int>("idSector")
                        .HasColumnType("int");

                    b.HasKey("idAsignacion");

                    b.HasIndex("idPersonal");

                    b.HasIndex("idSector");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("Satizen_Api.Models.Institucion", b =>
                {
                    b.Property<int>("idInstitucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idInstitucion"));

                    b.HasKey("idInstitucion");

                    b.ToTable("Instituciones");
                });

            modelBuilder.Entity("Satizen_Api.Models.Paciente", b =>
                {
                    b.Property<int>("idPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPaciente"));

                    b.Property<DateTime>("fechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<int?>("idInstitucion")
                        .HasColumnType("int");

                    b.Property<int?>("idUsuario")
                        .HasColumnType("int");

                    b.Property<string>("nombrePaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numeroHabitacionPaciente")
                        .HasColumnType("int");

                    b.Property<string>("observacionPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPaciente");

                    b.HasIndex("idInstitucion");

                    b.HasIndex("idUsuario");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Satizen_Api.Models.Permiso", b =>
                {
                    b.Property<int>("idPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPermiso"));

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPermiso");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            idPermiso = 1,
                            tipo = "Crear"
                        },
                        new
                        {
                            idPermiso = 2,
                            tipo = "Leer"
                        },
                        new
                        {
                            idPermiso = 3,
                            tipo = "Eliminar"
                        },
                        new
                        {
                            idPermiso = 4,
                            tipo = "Actualizar"
                        });
                });

            modelBuilder.Entity("Satizen_Api.Models.Personal", b =>
                {
                    b.Property<int>("idPersonal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPersonal"));

                    b.Property<int>("celularPersonal")
                        .HasColumnType("int");

                    b.Property<string>("correoPersonal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idInstitucion")
                        .HasColumnType("int");

                    b.Property<string>("nombrePersonal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rolPersonal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("telefonoPersonal")
                        .HasColumnType("int");

                    b.HasKey("idPersonal");

                    b.ToTable("Personal");
                });

            modelBuilder.Entity("Satizen_Api.Models.Roles", b =>
                {
                    b.Property<int>("idRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRol"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("idPermiso")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idRol");

                    b.HasIndex("idPermiso");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            idRol = 1,
                            descripcion = "Soy administrador",
                            idPermiso = 1,
                            nombre = "Administrador"
                        },
                        new
                        {
                            idRol = 2,
                            descripcion = "Soy médico",
                            idPermiso = 2,
                            nombre = "Medico"
                        },
                        new
                        {
                            idRol = 3,
                            descripcion = "Soy enfermero",
                            idPermiso = 2,
                            nombre = "Enfermero"
                        });
                });

            modelBuilder.Entity("Satizen_Api.Models.Sector", b =>
                {
                    b.Property<int>("idSector")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSector"));

                    b.Property<int>("idInstitucion")
                        .HasColumnType("int");

                    b.Property<string>("nombreSector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSector");

                    b.ToTable("Sector");
                });

            modelBuilder.Entity("Satizen_Api.Models.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<DateTime?>("estadoUsuario")
                        .HasColumnType("datetime2");

                    b.Property<int?>("idRoles")
                        .HasColumnType("int");

                    b.Property<string>("nombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idUsuario");

                    b.HasIndex("idRoles");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Satizen_Api.Models.Asignacion", b =>
                {
                    b.HasOne("Satizen_Api.Models.Personal", "personal")
                        .WithMany()
                        .HasForeignKey("idPersonal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Satizen_Api.Models.Sector", "sector")
                        .WithMany()
                        .HasForeignKey("idSector")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("personal");

                    b.Navigation("sector");
                });

            modelBuilder.Entity("Satizen_Api.Models.Paciente", b =>
                {
                    b.HasOne("Satizen_Api.Models.Institucion", "institucion")
                        .WithMany()
                        .HasForeignKey("idInstitucion");

                    b.HasOne("Satizen_Api.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario");

                    b.Navigation("institucion");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("Satizen_Api.Models.Roles", b =>
                {
                    b.HasOne("Satizen_Api.Models.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("idPermiso");

                    b.Navigation("Permiso");
                });

            modelBuilder.Entity("Satizen_Api.Models.Usuario", b =>
                {
                    b.HasOne("Satizen_Api.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("idRoles");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
