// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Satizen_Api.Data;

#nullable disable

namespace Satizen_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240529190722_Llamados")]
    partial class Llamados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Satizen_Api.Modelos.Llamado", b =>
                {
                    b.Property<int>("idLlamado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLlamado"));

                    b.Property<string>("estadoLlamado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaHoraLlamado")
                        .HasColumnType("datetime2");

                    b.Property<int>("idPaciente")
                        .HasColumnType("int");

                    b.Property<int>("idPersonal")
                        .HasColumnType("int");

                    b.Property<string>("observacionLlamado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prioridadLlamado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idLlamado");

                    b.ToTable("Llamados");
                });
#pragma warning restore 612, 618
        }
    }
}
