// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyec_Satizen_Api.Datos;

#nullable disable

namespace Proyec_Satizen_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240602021116_AgregarBaseDatos")]
    partial class AgregarBaseDatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyec_Satizen_Api.Models.InstitucionModels", b =>
                {
                    b.Property<int>("idInstitucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idInstitucion"));

                    b.Property<string>("celularInstitucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correoInstitucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccionInstitucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreInstitucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefonoInstitucion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idInstitucion");

                    b.ToTable("Institucions");
                });
#pragma warning restore 612, 618
        }
    }
}
