// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Satizen_Api.Data;

#nullable disable

namespace Satizen_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Satizen_Api.models.Dto.Contacto", b =>
                {
                    b.Property<int>("idContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idContacto"));

                    b.Property<DateTime>("FechaInicioValidez")
                        .HasColumnType("datetime2");

                    b.Property<int>("celularAcompananteP")
                        .HasColumnType("int");

                    b.Property<int>("celularPaciente")
                        .HasColumnType("int");

                    b.Property<DateTime?>("eliminado")
                        .HasColumnType("datetime2");

                    b.Property<string>("estadoContacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idPaciente")
                        .HasColumnType("int");

                    b.HasKey("idContacto");

                    b.ToTable("Contactos");
                });
#pragma warning restore 612, 618
        }
    }
}
