// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyec_Satizen_Api.Datos;

#nullable disable

namespace Proyec_Satizen_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyec_Satizen_Api.Models.InstitucionModels", b =>
                {
                    b.Property<int>("idInstitucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idInstitucion"));

                    b.Property<string>("celularInstitucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correoInstitucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccionInstitucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreInstitucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefonoInstitucion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idInstitucion");

                    b.ToTable("Institucions");

                    b.HasData(
                        new
                        {
                            idInstitucion = 1,
                            celularInstitucion = "6473467326",
                            correoInstitucion = "santaqgmail.com",
                            direccionInstitucion = "Caleee",
                            nombreInstitucion = "Santa",
                            telefonoInstitucion = "53625362"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
